### ISSUE TITLE
<WakaTime> Got response Error

### ISSUE THREAD

**Issue by sathyarajshetigar** [vladfaust/unity-wakatime#16] opened 2019-04-05 11:24 UTC
This is what i get 
```
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

instead of this 
```
<WakaTime> Got response
{"data":{"id":"***************************************"}}
```

**Comment by vladfaust** [comment] 2019-04-05 12:19
Duplicate of #13

**Closed by vladfaust** 2019-04-05 12:19 UTC
