### ISSUE TITLE
ArgumentException: JSON parse error: Invalid value.

### ISSUE THREAD

**Issue by oxysoft** [vladfaust/unity-wakatime#18] opened 2019-05-24 01:07 UTC
Full stacktrace:

```
ArgumentException: JSON parse error: Invalid value.
UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:50)
UnityEngine.JsonUtility.FromJson[T] (System.String json) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:33)
WakaTime.Plugin+<>c__DisplayClass21_0.<SendHeartbeat>b__0 (UnityEngine.AsyncOperation operation) (at Library/PackageCache/com.vladfaust.unitywakatime@b8a1d9f726608a3517fade7d045c7c629a57c302/Editor/Plugin.cs:157)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at C:/buildslave/unity/build/Runtime/Export/AsyncOperation.cs:21)
```

It spams like crazy when I run the game, but I've seen the same exception in edit mode too. (but from a different event, I'm guessing)

Unity 2018.3.7f1

**Comment by Hermesiss** [comment] 2019-05-24 06:53
Duplicate of #13 
Prioritized 👌

**Closed by Hermesiss** 2019-05-24 06:53 UTC
Labels: duplicate
